"""Decision D2 sensitivity: compare RH1 and RH2 across false-alarm budgets.

Usage: python scripts/budget_report.py
Reads `phase2/results/m5_rehearsal.npz` (the primary budget, from the config) and `phase2/results/budget/<budget>/m5_rehearsal.npz`. Writes phase2/D2-Budget-Sensitivity.md.
Exploratory. RH3 and RH4 are not re-run under the budgets.
"""

import logging
import sys
from pathlib import Path
from typing import Dict, List

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.eval_module.pooled import collect_diffs, pooled_bootstrap  # noqa: E402
from src.sim_module.config import false_alarm_budget  # noqa: E402
from src.utils import log_environment  # noqa: E402

logger = logging.getLogger(__name__)
ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "phase2" / "results"
OUTPUT = ROOT / "phase2" / "D2-Budget-Sensitivity.md"
RH1_POOL, RH2_POOL, LAGS, MARGIN = ("SC07", "SC08", "SC09", "SC17", "SC19", "SC25"), ("SC08", "SC17", "SC25"), (0, 2, 8), 2.0
BUDGETS = (1.0, 5.0, 20.0, 30.0, 50.0, 150.0)
PRIMARY = false_alarm_budget()


def source(budget: float) -> Path:
    """Stored replicates for a budget (the primary budget is the default run)."""
    return RESULTS / "m5_rehearsal.npz" if budget == PRIMARY else RESULTS / "budget" / f"{budget:g}" / "m5_rehearsal.npz"


def summarize(store: Dict[str, np.ndarray], lag: int) -> List[str]:
    """RH1 (windows, harm units, and with CCA over all testable indicators), RH2, and the conventional arm's mean TAFD at one lag."""
    rng = np.random.default_rng(3 + lag)
    rh1 = pooled_bootstrap(collect_diffs(store, RH1_POOL, lag, "conventional", "CCA (component split)"), MARGIN, rng)
    harm = pooled_bootstrap(collect_diffs(store, RH1_POOL, lag, "avoided", None), 1.0, rng)
    full = pooled_bootstrap(collect_diffs(store, RH1_POOL, lag, "conventional", "CCA (all testable)"), MARGIN, rng)
    rh2 = pooled_bootstrap(collect_diffs(store, RH2_POOL, lag, "conventional", "calibration arm"), 0.0, rng)
    conv = pooled_bootstrap(collect_diffs(store, RH1_POOL, lag, "conventional", None), 0.0, rng)
    return [f"{rh1[0]:+.2f} [{rh1[1]:+.2f}, {rh1[2]:+.2f}] (p = {rh1[3]:.3f})", f"{harm[0]:+.2f} (p = {harm[3]:.3f})", f"{full[0]:+.2f} [{full[1]:+.2f}, {full[2]:+.2f}]",
            f"{rh2[0]:+.2f} [{rh2[1]:+.2f}, {rh2[2]:+.2f}]", f"{conv[0]:.1f}"]


def main() -> int:
    """Build the comparison table."""
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    lines = ["# D2 sensitivity: RH1 and RH2 under different false-alarm budgets (exploratory)", "",
             "Generated by `scripts/budget_report.py`. The false-alarm budget is the system-level rate of alert episodes per 1,000 monitored windows at which every system is calibrated (decision D2). "
             "With windows of 7 to 14 days, 5 per 1,000 is one false alarm every 3.8 to 7.7 years, 20 about one every 1 to 2 years, 50 one every 5 to 10 months, and 150 one every 1 to 3 months. "
             f"The primary budget is {PRIMARY:g} (decision D2, section 16.18); 5 was the earlier primary. RH1 is the pooled reduction in windows against the D23 margin of {MARGIN:g} windows, with exposure avoided in baseline-windows of harm (anchor 1.00). "
             "The last column is the conventional arm's own mean TAFD in the pooled cells (capped at the horizon), which shows how fast the comparator is at each budget. "
             f"RH3 and RH4 are not re-run. Environment: {log_environment()}", "",
             "| Budget per 1,000 windows | Lag | RH1 reduction [95% CI] | RH1 exposure avoided | RH1 with CCA over all testable indicators | RH2 reduction [95% CI] | Conventional mean TAFD |", "|---|---|---|---|---|---|---|"]
    for budget in BUDGETS:
        path = source(budget)
        if not path.exists():
            lines.append(f"| {budget:g} | | not run | | | | |")
            continue
        store = dict(np.load(path))
        for lag in LAGS:
            a, b, c, d, e = summarize(store, lag)
            label = f"{budget:g}" if lag == LAGS[0] else ""
            lines.append(f"| {label} | {lag} | {a} | {b} | {c} | {d} | {e} |")
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    logger.info("Wrote %s", OUTPUT.name)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
