"""Decision D3 sensitivity: compare RH1 and RH2 across the severity weightings.

Usage: python scripts/d3_report.py
Reads `phase2/results/m5_rehearsal.npz` (the primary scheme) and `phase2/results/d3/<scheme>/m5_rehearsal.npz` for each scheme run by
`scripts/d3_schemes.py`. Writes phase2/D3-Sensitivity.md. Exploratory. RH3 and RH4 are not re-run under the schemes.
"""

import logging
import sys
from pathlib import Path
from typing import Dict, List

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.eval_module.pooled import collect_diffs, pooled_bootstrap  # noqa: E402
from src.utils import log_environment  # noqa: E402

logger = logging.getLogger(__name__)
ROOT = Path(__file__).resolve().parent.parent
RESULTS, D3 = ROOT / "phase2" / "results", ROOT / "phase2" / "results" / "d3"
OUTPUT = ROOT / "phase2" / "D3-Sensitivity.md"
RH1_POOL, RH2_POOL, LAGS, MARGIN = ("SC07", "SC08", "SC09", "SC17", "SC19", "SC25"), ("SC08", "SC17", "SC25"), (0, 2, 8), 2.0
LABELS = {"primary": "Primary (1:7.1:100, missed = 2.4x; pooled raters)", "rater_1": "Rater 1 alone (1:5:50, missed = 3x)", "rater_2": "Rater 2 alone (1:10:200, missed = 2x)",
          "range_high": "Top of rater 2's class ranges (1:20:1000, missed = 2.4x)", "fn_factor_1_5": "Missed deterioration 1.5x (1:7.1:100)",
          "fn_factor_5": "Missed deterioration 5x (1:7.1:100)", "flat": "Flat (1:1:1, missed = 1x)"}


def summarize(store: Dict[str, np.ndarray], lag: int) -> List[str]:
    """RH1 (window and harm units, and with CCA over all testable indicators) and RH2 at one lag: estimate [95% CI] and the one-sided p."""
    rng = np.random.default_rng(3 + lag)
    base = float(store["baseline_rhe"][0])
    rh1 = pooled_bootstrap(collect_diffs(store, RH1_POOL, lag, "conventional", "CCA (component split)"), MARGIN, rng)
    harm = pooled_bootstrap(collect_diffs(store, RH1_POOL, lag, "avoided", None), base, rng)
    rh2 = pooled_bootstrap(collect_diffs(store, RH2_POOL, lag, "conventional", "calibration arm"), 0.0, rng)
    full = pooled_bootstrap(collect_diffs(store, RH1_POOL, lag, "conventional", "CCA (all testable)"), MARGIN, rng)
    return [f"{rh1[0]:+.2f} [{rh1[1]:+.2f}, {rh1[2]:+.2f}] (p = {rh1[3]:.3f})", f"{harm[0] / base:+.2f} baseline-windows (p = {harm[3]:.3f})",
            f"{rh2[0]:+.2f} [{rh2[1]:+.2f}, {rh2[2]:+.2f}]", f"{full[0]:+.2f} [{full[1]:+.2f}, {full[2]:+.2f}] (p = {full[3]:.3f})"]


def main() -> int:
    """Build the comparison table."""
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    sources = {"primary": RESULTS / "m5_rehearsal.npz", **{n: D3 / n / "m5_rehearsal.npz" for n in LABELS if n != "primary"}}
    lines = ["# D3 sensitivity: RH1 and RH2 under alternative severity weightings (exploratory)", "",
             "Generated by `scripts/d3_report.py`. Each scheme re-levels the scenario catalog against the same harm targets, so every scheme sees the same harm ratios, "
             "and reruns the RH1 and RH2 rehearsal (200 replicates per cell, the same fresh seeds). The primary scheme is the pooled elicited one (decision D3, two raters). RH1 is the pooled "
             f"reduction in windows against the D23 margin of {MARGIN:g} windows, at each label lag. The harm-unit column is the exposure avoided in units of one baseline-window of harm "
             "(the D23 anchor is 1.00), with the one-sided p against that anchor. RH2 is the calibration arm against the performance arm (positive favors the calibration arm). "
             "RH3 and RH4 are not re-run. A scheme whose harm targets cannot be reached under its weights is listed as not run. "
             f"Environment: {log_environment()}", "", "| Scheme | Lag | RH1 reduction in windows [95% CI] | RH1 in harm units | RH2 reduction [95% CI] | RH1 with CCA over all testable indicators |", "|---|---|---|---|---|---|"]
    notes: List[str] = []
    for name, path in sources.items():
        if not path.exists():
            lines.append(f"| {LABELS[name]} | | not run (harm targets unreachable, or the run did not finish) | | | |")
            continue
        store = dict(np.load(path))
        log = (path.parent / "relevel.log")
        short = [ln.split("WARNING: ")[-1] for ln in log.read_text(encoding="utf-8").splitlines() if "using the cap" in ln] if log.exists() else []
        if short:
            notes.append(f"**{LABELS[name]}**: " + "; ".join(short))
        for lag in LAGS:
            a, b, c, d = summarize(store, lag)
            lines.append(f"| {LABELS[name] if lag == LAGS[0] else ''} | {lag} | {a} | {b} | {c} | {d} |")
    if notes:
        lines += ["", "## Levels that fell short of their harm targets", "", "The plausibility cap could not produce the target harm ratio under the scheme, so the cap level was used and the cell has a smaller effect than in the primary scheme.", ""] + [f"- {n}" for n in notes]
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    logger.info("Wrote %s", OUTPUT.name)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
