"""Solve each implemented perturbation's parameter for target harm ratios and report what is attainable.

Usage: python scripts/harm_scaled_levels.py
Writes phase2/Harm-Scaled-Levels.md. The catalog is not changed by this script.
"""

import logging
import sys
from pathlib import Path
from typing import Any, Dict, List

import numpy as np
import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.eval_module.metrics import auroc, ece, sensitivity, specificity  # noqa: E402
from src.sim_module import (AXES, DeployedModel, PerturbationConfig, PerturbationFactory, SyntheticWorld, baselines_for,  # noqa: E402
                            load_config, parse_level, ratio_at, solve_levels)
from src.utils import set_seed  # noqa: E402

logger = logging.getLogger(__name__)

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "phase2" / "Harm-Scaled-Levels.md"
TARGETS = (1.15, 1.35, 1.75)
N = 300_000


def effects(world: SyntheticWorld, model: DeployedModel, kind: str, value: float, mode: Any) -> Dict[str, float]:
    """Population effects at a solved level, for judging plausibility."""
    pert = PerturbationFactory(kind)(PerturbationConfig(level_value=value, mode=mode))
    b = pert.generate(world, model, N, np.random.default_rng(12), 1.0)
    return {"AUROC": auroc(b.y, b.reported_p), "Se": sensitivity(b.y, b.decision), "Sp": specificity(b.y, b.decision),
            "ECE": ece(b.y, b.reported_p), "prev": float(b.y.mean())}


def main() -> int:
    """Run the solver over the implemented scenarios and write the report."""
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    cfg = load_config()
    set_seed(cfg.seed)
    world = SyntheticWorld(cfg.generator, cfg.harm)
    model = DeployedModel(cfg.generator).fit(world, np.random.default_rng(cfg.seed))
    catalog = {s["id"]: s for s in yaml.safe_load((ROOT / "phase2" / "scenarios.yaml").read_text(encoding="utf-8"))}
    base = baselines_for(world, model, cfg, N)
    SCENARIOS = tuple(k for k, s in catalog.items() if s["family"] != "control" and s["perturbation"]["type"] in AXES)  # noqa: N806
    lines = ["# Harm-scaled levels", "",
             "Generated by `scripts/harm_scaled_levels.py`. For each implemented perturbation, the parameter value at full effect that gives a target ratio of "
             "expected residual harm exposure to baseline, or the reason it cannot be reached within a plausibility cap. The caps are my placeholders. "
             f"{N:,} cases per evaluation, so ratios carry about 1 percent noise. Harm weights, the reviewer model, and kappa (0.25) are placeholders. "
             "The catalog is unchanged.", "",
             f"Baseline expected RHE at this sample size: {base['pooled']:.2f} per 1,000 pooled and {base['subgroup']:.2f} in the predefined subgroup. Ratios are onset ratios (decision D18: the larger of the pooled and subgroup ratios). Targets: 1.15 is deliberately below the kappa threshold of 1.25, 1.35 is "
             "just above it, and 1.75 is well above.", "",
             "| Scenario | Mechanism | Axis and cap | Ratio at the catalog's high level | Level for 1.15 | Level for 1.35 | Level for 1.75 | Monotone |", "|---|---|---|---|---|---|---|---|"]
    detail: List[str] = []
    attainable_135: List[str] = []
    for sid in SCENARIOS:
        spec = catalog[sid]["perturbation"]
        kind, mode = spec["type"], spec.get("mode")
        axis = AXES[kind]
        high = ratio_at(kind, parse_level(spec["levels"]["high"]), world, model, cfg, N, mode, base)
        sols = solve_levels(kind, TARGETS, world, model, cfg, N, mode)
        cells = [f"{s.value:.3g}" if s.attainable else f"not reachable (max {s.max_ratio:.2f})" for s in sols]
        lines.append(f"| {sid} | {kind}{' (' + mode + ')' if mode else ''} | {axis.unit}, cap {axis.cap:g} | {high:.2f} | {' | '.join(cells)} | {'yes' if sols[0].monotone else 'no'} |")
        if sols[1].attainable:
            attainable_135.append(sid)
        for s in sols:
            if s.attainable and s.value is not None:
                e = effects(world, model, kind, s.value, mode)
                detail.append(f"| {sid} | {s.target} | {s.value:.3g} | {e['AUROC']:.3f} | {e['Se']:.3f} | {e['Sp']:.3f} | {e['ECE']:.4f} | {e['prev']:.3f} |")
        logger.info("%s: %s", sid, cells)
    lines += ["", f"Scenarios that can reach a ratio of 1.35 within the cap: {', '.join(attainable_135) or 'none'}. "
              f"Those that cannot: {', '.join(s for s in SCENARIOS if s not in attainable_135)}.", "",
              "## Effects at the solved levels", "", "| Scenario | Target ratio | Level | AUROC | Se | Sp | ECE | Prevalence |", "|---|---|---|---|---|---|---|---|"] + detail
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    logger.info("Wrote %s", OUTPUT.name)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
