"""Milestones M1 and M2 report: baseline bands, per-cell effects, expected RHE, and sub-threshold cells.

Usage: python scripts/m2_expected_rhe.py
Writes phase2/M1-M2-Results.md. All numbers are population-level Monte Carlo values from the Tier 1 simulator.
"""

import logging
import sys
from pathlib import Path
from typing import Any, Dict, List

import numpy as np
import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.eval_module.metrics import auroc, calibration_slope, ece, npv, ppv, sensitivity, specificity  # noqa: E402
from src.sim_module import (DeployedModel, PerturbationConfig, PerturbationFactory, SyntheticWorld,  # noqa: E402
                            expected_rhe, load_config, parse_level, registered_perturbations)
from src.utils import log_environment, set_seed  # noqa: E402

logger = logging.getLogger(__name__)

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "phase2" / "M1-M2-Results.md"
KAPPAS = (0.10, 0.25, 0.50)
CHUNKS = 10


def summarize(batch: Any, cfg: Any) -> Dict[str, float]:
    """Population metrics and expected RHE (with a chunk-based Monte Carlo standard error)."""
    step = batch.n // CHUNKS
    rhe = [expected_rhe(batch.slice(i * step, (i + 1) * step), cfg) for i in range(CHUNKS)]
    return {"Se": sensitivity(batch.y, batch.decision), "Sp": specificity(batch.y, batch.decision),
            "AUROC": auroc(batch.y, batch.reported_p), "ECE": ece(batch.y, batch.reported_p),
            "slope": calibration_slope(batch.y, batch.reported_p), "prev": float(batch.y.mean()),
            "PPV": ppv(batch.y, batch.decision), "NPV": npv(batch.y, batch.decision),
            "RHE": float(np.mean(rhe)), "RHE_se": float(np.std(rhe, ddof=1) / np.sqrt(CHUNKS))}


def m1_section(cfg: Any) -> List[str]:
    """Distribution of the baseline metrics over the M1 seeds, against the pre-fixed bands."""
    bands, n_eval = cfg.m1_bands, cfg.stream.baseline_windows * cfg.stream.cases_per_window
    rows = []
    for seed in range(bands.seeds):
        world = SyntheticWorld(cfg.generator, cfg.harm)
        model = DeployedModel(cfg.generator).fit(world, np.random.default_rng(seed))
        b = model.apply(world.sample(n_eval, np.random.default_rng(10_000 + seed)))
        rows.append((ece(b.y, b.reported_p), auroc(b.y, b.reported_p), sensitivity(b.y, b.decision)))
    arr = np.array(rows)
    return ["## M1. Baseline against the pre-fixed bands", "",
            f"{bands.seeds} seeds, each with its own training sample and a {n_eval:,}-case baseline evaluation.", "",
            "| Metric | Band | Mean | Min | Max |", "|---|---|---|---|---|",
            f"| ECE | at most {bands.ece_max} | {arr[:, 0].mean():.4f} | {arr[:, 0].min():.4f} | {arr[:, 0].max():.4f} |",
            f"| AUROC | {bands.auroc_min} to {bands.auroc_max} | {arr[:, 1].mean():.4f} | {arr[:, 1].min():.4f} | {arr[:, 1].max():.4f} |",
            f"| Sensitivity | {cfg.generator.target_sensitivity} +/- {bands.sensitivity_tolerance} | {arr[:, 2].mean():.4f} | {arr[:, 2].min():.4f} | {arr[:, 2].max():.4f} |", ""]


def main() -> int:
    """Compute and write the report."""
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    cfg = load_config()
    set_seed(cfg.seed)
    world = SyntheticWorld(cfg.generator, cfg.harm)
    model = DeployedModel(cfg.generator).fit(world, np.random.default_rng(cfg.seed))
    n = cfg.tolerances.population_cases
    scenarios = {s["id"]: s for s in yaml.safe_load((ROOT / "phase2" / "scenarios.yaml").read_text(encoding="utf-8"))}
    base = summarize(model.apply(world.sample(n, np.random.default_rng(11))), cfg)
    lines = ["# Phase II M1 and M2 results (Tier 1, synthetic)", "",
             "Generated by `scripts/m2_expected_rhe.py`. Population-level Monte Carlo values from the simulator with "
             f"{n:,} cases per cell. Severity weights, the reviewer model, and kappa are placeholders (design decisions D3 and D4).",
             "", f"Environment: {log_environment()}", ""] + m1_section(cfg)
    lines += ["## Baseline population values", "",
              "| Se | Sp | AUROC | ECE | Calibration slope | Prevalence | PPV | NPV | Expected RHE per 1,000 |", "|---|---|---|---|---|---|---|---|---|",
              f"| {base['Se']:.3f} | {base['Sp']:.3f} | {base['AUROC']:.3f} | {base['ECE']:.4f} | {base['slope']:.3f} | {base['prev']:.3f} | {base['PPV']:.3f} | {base['NPV']:.3f} | {base['RHE']:.2f} (SE {base['RHE_se']:.2f}) |", ""]
    lines += ["## M2. Cell effects and expected RHE at full effect", "",
              "RHE ratio is the expected RHE divided by baseline. A cell is **sub-threshold** at a kappa when its ratio is below 1 + kappa "
              "and it would have no onset. Ramped shapes reach the same full effect at the end of their ramp. "
              "Only the data and model layer is implemented, so delay harm and reviewer or workflow faults are absent.", "",
              "| Scenario | Level | Se | Sp | AUROC | ECE | Slope | Prev | RHE | RHE ratio | Sub-threshold at kappa 0.10 / 0.25 / 0.50 |", "|---|---|---|---|---|---|---|---|---|---|---|"]
    sub_counts = {k: 0 for k in KAPPAS}
    cells = 0
    implemented = set(registered_perturbations())
    for sid in [k for k, s in scenarios.items() if s["family"] != "control" and s["perturbation"]["type"] in implemented]:
        spec = scenarios[sid]["perturbation"]
        assert spec["type"] in registered_perturbations()
        for level in ("low", "medium", "high"):
            pert = PerturbationFactory(spec["type"])(PerturbationConfig(level_value=parse_level(spec["levels"][level]), mode=spec.get("mode")))
            r = summarize(pert.generate(world, model, n, np.random.default_rng(12), 1.0), cfg)
            ratio = r["RHE"] / base["RHE"]
            flags = ["yes" if ratio < 1 + k else "no" for k in KAPPAS]
            for k, f in zip(KAPPAS, flags):
                sub_counts[k] += f == "yes"
            cells += 1
            lines.append(f"| {sid} | {level} | {r['Se']:.3f} | {r['Sp']:.3f} | {r['AUROC']:.3f} | {r['ECE']:.4f} | {r['slope']:.3f} | {r['prev']:.3f} | {r['RHE']:.2f} | {ratio:.2f} | {' / '.join(flags)} |")
    lines += ["", f"Sub-threshold cells among the {cells} implemented (scenario, level) combinations: "
              + "; ".join(f"kappa {k}: {v}" for k, v in sub_counts.items()) + ".", "",
              "## Calibration-slope mechanisms compared", "",
              "SC03 changes the world (`outcome_link`): calibration and performance move together. SC23 changes only the displayed confidence "
              "(`output_transform`): ranking and decisions are exactly unchanged. The SC03 levels are provisional. They must keep the change in "
              "AUROC inside AUROC's own yellow margin, which milestone M4 produces.", "",
              "| Slope | Mechanism | AUROC | Change in AUROC | ECE | Calibration slope | Se | RHE ratio |", "|---|---|---|---|---|---|---|---|"]
    for slope in (0.95, 0.9, 0.85, 0.75, 0.6):
        for mode in ("outcome_link", "output_transform"):
            pert = PerturbationFactory("slope_and_intercept_drift")(PerturbationConfig(level_value=slope, mode=mode))
            r = summarize(pert.generate(world, model, n, np.random.default_rng(12), 1.0), cfg)
            lines.append(f"| {slope} | {mode} | {r['AUROC']:.3f} | {r['AUROC'] - base['AUROC']:+.3f} | {r['ECE']:.4f} | {r['slope']:.3f} | {r['Se']:.3f} | {r['RHE'] / base['RHE']:.2f} |")
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    logger.info("Wrote %s", OUTPUT.name)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
