"""Milestone M5c: the RH3 mixture-stream test (design section 9.1).

Usage: python scripts/m5c_rh3_mixture.py
Streams carry one or two random reviewer failures (SC10, SC11, SC13) at random levels and start windows. A window is positive when
its expected RHE reaches 1 + kappa of baseline. Logistic models fit on 1,000 streams are scored on 1,000 independent ones. The gain is the AUROC of
H1, H4, H5, H6 minus that of H1 alone, with a stream-level bootstrap. Writes phase2/M5c-RH3-Mixture.md. Exploratory, one seed, Tier 1 synthetic
data with assumed reviewer parameters. Not adjusted for the four-hypothesis family: RH1, RH2, RH4 are not yet run.
"""

import json
import logging
import sys
from dataclasses import replace
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np
import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.monitor_module.mixture import WindowRatio, auroc_gain, mixture_features  # noqa: E402
from src.monitor_module.review_layer import REVIEW_ORDER  # noqa: E402
from src.sim_module import DeployedModel, SyntheticWorld, load_config, parse_level  # noqa: E402
from src.sim_module.config import report_path, results_dir  # noqa: E402
from src.utils import log_environment, set_seed  # noqa: E402

logger = logging.getLogger(__name__)
ROOT = Path(__file__).resolve().parent.parent
S_FIT, S_EVAL, LAGS, AUDIT, DEADLINE, COVERAGE = 1000, 1000, (0, 2, 8), 0.2, 5.0, 0.95
SETS = {"H1 alone": ["H1"], "H1 + H4 + H5 + H6 (RH3)": ["H1", "H4", "H5", "H6"], "H1 to H6": list(REVIEW_ORDER)}
SCENARIOS = ("SC10", "SC11", "SC13")
# Failure mixes in the order SC10, SC11, SC13 (decision D22): equal is primary, the other two are reported beside it.
MIXES: List[Tuple[str, Optional[Sequence[float]]]] = [("equal (primary)", None), ("SC11-heavy (80 percent)", (0.1, 0.8, 0.1)), ("SC10-heavy (80 percent)", (0.8, 0.1, 0.1))]


def main() -> int:
    """Run the test and write the report."""
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    cfg0 = load_config()
    cfg = replace(cfg0, reviewer=replace(cfg0.reviewer, deadline=DEADLINE, coverage=COVERAGE))
    set_seed(cfg.seed)
    world = SyntheticWorld(cfg.generator, cfg.harm)
    model = DeployedModel(cfg.generator).fit(world, np.random.default_rng(cfg.seed))
    scenarios = {s["id"]: s for s in yaml.safe_load((ROOT / "phase2" / "scenarios.yaml").read_text(encoding="utf-8"))}
    levels: Dict[str, Sequence[float]] = {scenarios[s]["perturbation"]["type"]: [parse_level(v) for v in scenarios[s]["perturbation"]["levels"].values()] for s in SCENARIOS}
    ratio = WindowRatio(cfg, model.apply(world.sample(200_000, np.random.default_rng(11))))
    col = {name: [REVIEW_ORDER.index(h) for h in hs] for name, hs in SETS.items()}
    rows: List[str] = []
    headline: Dict[str, Dict[str, float]] = {}
    shares: List[str] = []
    for mix, weights in MIXES:
        fit_x, fit_y, _ = mixture_features(S_FIT, 11, cfg, world, model, levels, ratio, LAGS, AUDIT, weights)
        eval_x, eval_y, counts = mixture_features(S_EVAL, 22, cfg, world, model, levels, ratio, LAGS, AUDIT, weights)
        logger.info("%s done (positive windows %.2f)", mix, eval_y.mean())
        shares.append(f"{mix}: {eval_y.mean():.0%} positive windows, {np.mean(np.array(counts) == 2):.0%} of streams with two failures")
        for lag in LAGS:
            for name in list(SETS)[1:]:
                r = auroc_gain(fit_y, fit_x[lag][:, :, col["H1 alone"]], fit_x[lag][:, :, col[name]], eval_y, eval_x[lag][:, :, col["H1 alone"]],
                               eval_x[lag][:, :, col[name]], np.random.default_rng(5))
                if mix.startswith("equal") and name == list(SETS)[1]:
                    headline[str(lag)] = {"estimate": r.gain, "lo": r.lo, "hi": r.hi, "p": r.p}
                rows.append(f"| {mix} | {lag} | {name} | {r.auroc_base:.3f} | {r.auroc_full:.3f} | {r.gain:+.3f} [{r.lo:+.3f}, {r.hi:+.3f}] | {r.p:.3f} |")
    lines = ["# Phase II M5c: RH3 mixture-stream test (exploratory)", "",
             "Generated by `scripts/m5c_rh3_mixture.py`.",
             "", f"Streams carry one or two random failures among SC10, SC11, and SC13 (abrupt, levels drawn from the catalog, start between windows {cfg.stream.s0_low} and "
             f"{cfg.stream.s0_high_abrupt}). A window is positive when its expected RHE reaches 1 + kappa ({cfg.harm.kappa:g}) of baseline. Logistic regression is fit on {S_FIT:,} streams "
             f"and scored on {S_EVAL:,} independent streams. The gain is the AUROC with the feature set minus the AUROC of H1 alone, with a bootstrap over whole streams. "
             f"Failure mixes (decision D22): {'; '.join(shares)}. Baseline review coverage {COVERAGE:.0%}, "
             f"deadline {DEADLINE:g} median review times, {AUDIT:.0%} audit for H5 (all placeholders). The p-value is one-sided (null: gain at most zero) and is not adjusted "
             "for the four-hypothesis family, because RH1, RH2, and RH4 are not yet run. The features are the standardized indicators, with H4 and H5 lagged by the label lag. "
             f"Environment: {log_environment()}", "", "| Failure mix | Lag | Feature set | AUROC, H1 alone | AUROC, set | Gain [95% CI] | p (one-sided) |", "|---|---|---|---|---|---|---|"] + rows + [""]
    (results_dir() / "rh3.json").write_text(json.dumps(headline, indent=1), encoding="utf-8")
    output = report_path("M5c-RH3-Mixture.md")
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    logger.info("Wrote %s", output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
