"""Milestone M5d: sensitivity of the RH3 gain to the failure mix and the assumed reviewer (design sections 9.1 and 11).

Usage: python scripts/m5d_rh3_sensitivity.py
Repeats the M5c test on smaller samples (300 fit and 300 evaluation streams per configuration) while varying one assumption at a time from
the M5c setting. Writes phase2/M5d-RH3-Sensitivity.md. Exploratory. It is a one-at-a-time sweep, not the full grid of design section 11.
"""

import logging
import sys
from dataclasses import replace
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import numpy as np
import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.monitor_module.mixture import WindowRatio, auroc_gain, mixture_features  # noqa: E402
from src.monitor_module.review_layer import REVIEW_ORDER  # noqa: E402
from src.sim_module import DeployedModel, SyntheticWorld, load_config, parse_level  # noqa: E402
from src.utils import log_environment, set_seed  # noqa: E402

logger = logging.getLogger(__name__)
ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "phase2" / "M5d-RH3-Sensitivity.md"
S_FIT, S_EVAL, LAGS, DEADLINE, COVERAGE = 300, 300, (0, 8), 5.0, 0.95
SCENARIOS = ("SC10", "SC11", "SC13")
RH3_SET = [REVIEW_ORDER.index(h) for h in ("H1", "H4", "H5", "H6")]
# name -> (reviewer overrides, audit fraction, mix weights in the order SC10, SC11, SC13, automation-bias level scale)
CONFIGS: List[Tuple[str, Dict[str, float], float, Optional[Sequence[float]], float]] = [
    ("M5c setting", {}, 0.20, None, 1.0),
    ("SC11-heavy mix (80 percent of failures)", {}, 0.20, (0.1, 0.8, 0.1), 1.0),
    ("SC10-heavy mix", {}, 0.20, (0.8, 0.1, 0.1), 1.0),
    ("Automation-bias levels halved", {}, 0.20, None, 0.5),
    ("Weaker reviewer recognition (beta0 = 0)", {"beta0": 0.0}, 0.20, None, 1.0),
    ("Stronger reviewer recognition (beta0 = 2)", {"beta0": 2.0}, 0.20, None, 1.0),
    ("Tighter deadline (3 median reviews)", {"deadline": 3.0}, 0.20, None, 1.0),
    ("Looser deadline (10 median reviews)", {"deadline": 10.0}, 0.20, None, 1.0),
    ("Audit 5 percent", {}, 0.05, None, 1.0),
]


def main() -> int:
    """Run the sweep and write the report."""
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    cfg0 = load_config()
    set_seed(cfg0.seed)
    world = SyntheticWorld(cfg0.generator, cfg0.harm)
    model = DeployedModel(cfg0.generator).fit(world, np.random.default_rng(cfg0.seed))
    scenarios = {s["id"]: s for s in yaml.safe_load((ROOT / "phase2" / "scenarios.yaml").read_text(encoding="utf-8"))}
    base_levels: Dict[str, List[float]] = {scenarios[s]["perturbation"]["type"]: [parse_level(v) for v in scenarios[s]["perturbation"]["levels"].values()]
                                            for s in SCENARIOS}
    population = model.apply(world.sample(200_000, np.random.default_rng(11)))
    rows: List[str] = []
    for i, (name, override, audit, weights, bias_scale) in enumerate(CONFIGS):
        params: Dict[str, Any] = {"deadline": DEADLINE, "coverage": COVERAGE, **override}
        cfg = replace(cfg0, reviewer=replace(cfg0.reviewer, **params))
        levels: Dict[str, Sequence[float]] = {k: ([v * bias_scale for v in vs] if k == "reviewer_acceptance_of_ai_errors" else vs) for k, vs in base_levels.items()}
        ratio = WindowRatio(cfg, population)
        fx, fy, _ = mixture_features(S_FIT, 11, cfg, world, model, levels, ratio, LAGS, audit, weights)
        ex, ey, _ = mixture_features(S_EVAL, 22, cfg, world, model, levels, ratio, LAGS, audit, weights)
        for lag in LAGS:
            r = auroc_gain(fy, fx[lag][:, :, [0]], fx[lag][:, :, RH3_SET], ey, ex[lag][:, :, [0]], ex[lag][:, :, RH3_SET], np.random.default_rng(5))
            rows.append(f"| {name} | {lag} | {ey.mean():.2f} | {r.auroc_base:.3f} | {r.auroc_full:.3f} | {r.gain:+.3f} [{r.lo:+.3f}, {r.hi:+.3f}] |")
        logger.info("%d/%d %s done", i + 1, len(CONFIGS), name)
    lines = ["# Phase II M5d: sensitivity of the RH3 gain (exploratory)", "",
             "Generated by `scripts/m5d_rh3_sensitivity.py`. The M5c test repeated on 300 fit and 300 evaluation streams per row, changing one assumption at a time. "
             f"Base setting: review coverage {COVERAGE:.0%}, deadline {DEADLINE:g} median reviews, 20 percent audit, equal failure mix. Gain is the AUROC of H1, H4, H5, H6 "
             "minus H1 alone, with a stream-level bootstrap interval. This is a one-at-a-time sweep and not the full grid promised in design section 11. "
             f"Environment: {log_environment()}", "",
             "| Configuration | Lag | Positive windows | AUROC, H1 alone | AUROC, RH3 set | Gain [95% CI] |", "|---|---|---|---|---|---|"] + rows + [""]
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    logger.info("Wrote %s", OUTPUT.name)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
