"""Computational analysis of the RH1 window margin (decision D5).

Usage: python scripts/margin_analysis.py
Needs `phase2/M3-M4-Pilot.md`. No new replicates: it reads the pilot's per-cell intervals and computes each cell's excess harm per window
of delay at full effect (a few seconds). Writes phase2/Margin-Analysis.md. Exploratory. The SC09 exposure uses the pooled baseline and understates
harm concentrated in the subgroup.
"""

import logging
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, List, Tuple

import numpy as np
import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.eval_module.margin import PilotRow, implied_margin, min_detectable, parse_pilot, pass_share, se_from_interval  # noqa: E402
from src.monitor_module import excess_ratio  # noqa: E402
from src.sim_module import HARM_POPULATION, DeployedModel, PerturbationConfig, PerturbationFactory, SyntheticWorld, load_config, parse_level, rhe_baselines  # noqa: E402
from src.utils import log_environment, set_seed  # noqa: E402

logger = logging.getLogger(__name__)
ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "phase2" / "Margin-Analysis.md"
POOL = ("SC07", "SC08", "SC09", "SC17", "SC19", "SC25")       # RH1 fair tests with a harm-defined onset that are built (design section 9.1)
WINDOW_MARGINS = (0.5, 1.0, 2.0, 3.0, 4.0)
DELTAS = (0.5, 1.0, 2.0)                               # baseline-windows of harm
LAGS = (0, 2, 8)


def excess_per_window(scenarios: Dict[str, Any], cfg: Any, world: SyntheticWorld, model: DeployedModel, baselines: Dict[str, float]) -> Dict[Tuple[str, str], float]:
    """Excess expected RHE per window at full effect, for each pooled scenario and level."""
    out: Dict[Tuple[str, str], float] = {}
    for sid in POOL:
        spec = scenarios[sid]["perturbation"]
        for level in ("medium", "high"):
            pert = PerturbationFactory(spec["type"])(PerturbationConfig(level_value=parse_level(spec["levels"][level]), mode=spec.get("mode")))
            out[(sid, level)] = excess_ratio(pert, world, model, cfg, 1.0, baselines)
    return out


def pooled_mean(rows: List[PilotRow], field: str) -> float:
    """Mean over scenarios of the mean over that scenario's cells (equal scenario weights)."""
    per: Dict[str, List[float]] = defaultdict(list)
    for r in rows:
        per[r.scenario].append(getattr(r, field))
    return float(np.mean([np.mean(v) for v in per.values()]))


def main() -> int:
    """Compute and write the report."""
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    cfg = load_config()
    set_seed(cfg.seed)
    world = SyntheticWorld(cfg.generator, cfg.harm)
    model = DeployedModel(cfg.generator).fit(world, np.random.default_rng(cfg.seed))
    scenarios = {s["id"]: s for s in yaml.safe_load((ROOT / "phase2" / "scenarios.yaml").read_text(encoding="utf-8"))}
    baselines = rhe_baselines(model.apply(world.sample(HARM_POPULATION, np.random.default_rng(11))), cfg)
    base = 1.0      # exposure is measured in baseline-windows of the stratum that defines onset (decision D18), so the unit is 1
    excess = excess_per_window(scenarios, cfg, world, model, baselines)
    rows = [r for r in parse_pilot((ROOT / "phase2" / "M3-M4-Pilot.md").read_text(encoding="utf-8")) if r.scenario in POOL]
    lines = ["# RH1 window margin: computational analysis (exploratory)", "",
             "Generated by `scripts/margin_analysis.py` from `phase2/M3-M4-Pilot.md`. Units: exposure is severity-weighted expected events per 1,000 cases, "
             "per 1,000 cases, summed over windows of 1,000 cases, and expressed in baseline-windows of harm: the unit is the baseline harm of the stratum that defines onset "
             f"(the pooled cohort, or the predefined subgroup for SC09; decision D18). The pooled scenarios are {', '.join(POOL)} "
             "(fair tests with a harm-defined onset that are built). "
             f"Environment: {log_environment()}", "",
             "## 1. What a harm-equivalent margin means in windows", "",
             "Each cell's excess expected RHE per window of delay at full effect, and the windows of earlier detection that avoid delta baseline-windows of harm "
             "(delta x baseline / excess). Harsher drift makes each window of delay costlier, so the same harm needs fewer windows.", "",
             "| Scenario | Level | Excess per window | As a share of baseline | Margin for delta = 0.5 | delta = 1 | delta = 2 |", "|---|---|---|---|---|---|---|"]
    for (sid, level), x in excess.items():
        lines.append(f"| {sid} | {level} | {x:.2f} | {x / base:.0%} | " + " | ".join(f"{implied_margin(x, base, d):.1f}" for d in DELTAS) + " |")
    pooled = list(excess.values())
    lines += ["", "Pooled harm-equivalent margin (mean over the medium and high cells of all pooled scenarios, SC09 included on its own subgroup baseline): " + ", ".join(f"delta = {d:g} gives {float(np.mean([implied_margin(x, base, d) for x in pooled])):.1f} windows" for d in DELTAS)
              + ". A margin of 1 window therefore corresponds to about "
              f"{float(np.mean([implied_margin(x, base, 1.0) for x in pooled])) ** -1:.2f} baseline-windows of harm.", ""]
    lines += ["", "## 2. How the pilot fares as the margin changes", "",
              "Share of cells whose interval's lower bound is at least the margin, and the pooled point estimate (equal scenario weights, no interval, because the "
              "pilot stores intervals and not replicate-level values). Window margins are in windows. Harm margins are delta baseline-windows of exposure avoided.", "",
              "| Lag | Cells | " + " | ".join(f"{m:g} window{'s' if m != 1 else ''}" for m in WINDOW_MARGINS) + " | " + " | ".join(f"{d:g} baseline-window{'s' if d != 1 else ''} of harm" for d in DELTAS)
              + " | Pooled reduction (windows) | Pooled exposure avoided |", "|---" * (2 + len(WINDOW_MARGINS) + len(DELTAS) + 2) + "|"]
    for lag in LAGS:
        cells = [r for r in rows if r.lag == lag]
        lo_w, lo_e = np.array([r.reduction_lo for r in cells]), np.array([r.exposure_lo for r in cells])
        lines.append(f"| {lag} | {len(cells)} | " + " | ".join(f"{pass_share(lo_w, m):.0%}" for m in WINDOW_MARGINS) + " | "
                     + " | ".join(f"{pass_share(lo_e, d * base):.0%}" for d in DELTAS) + f" | {pooled_mean(cells, 'reduction'):+.1f} | {pooled_mean(cells, 'exposure'):+.2f} |")
    se = np.array([se_from_interval(r.reduction_lo, r.reduction_hi) for r in rows])
    lines += ["", "## 3. Resolution floor", "",
              f"Standard errors of the reduction in the pooled cells (150 replicates each): median {np.median(se):.2f} windows, largest {se.max():.2f}. "
              f"Smallest reduction detected with 80 percent power at a one-sided 5 percent level: median {min_detectable(float(np.median(se))):.2f} windows, "
              f"worst cell {min_detectable(float(se.max())):.2f}. A margin below the worst-cell figure cannot be told from zero in every cell at this replicate count.", ""]
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    logger.info("Wrote %s", OUTPUT.name)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
