"""Validate Phase I requirements against saved sources and the indicator instrument.

Checks: unique IDs; every quote is a verbatim substring of the saved source text (after
whitespace, case, and punctuation normalization); indicator IDs exist; domains and
measurability codes are valid. Renders phase1/Assurance-Control-Matrix.md.

Usage: python scripts/validate_requirements.py
"""

import logging
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, List, Optional

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
from validate_indicators import INDICATOR_DIR, load_records, load_schema  # noqa: E402

logger = logging.getLogger(__name__)

ROOT = Path(__file__).resolve().parent.parent
PHASE1 = ROOT / "phase1"
OUTPUT = PHASE1 / "Assurance-Control-Matrix.md"
PRINTED_PAGE = re.compile(r"Page\s+(\d+)\s+NIST AI 100-1")


def _norm(text: str) -> str:
    """Lowercase and keep only letters and digits, so line breaks and dashes do not matter."""
    return re.sub(r"[^a-z0-9]+", "", text.lower())


def locate_page(source_text: str, quote: str) -> Optional[str]:
    """Return 'PDF p. N' from form-feed page breaks, plus the printed page if one is on that page.

    None when the source has no page breaks or the quote's opening is not found on a single page.
    """
    pages = source_text.split("\f")
    if len(pages) < 2:
        return None
    probe = _norm(quote)[:50]
    for index, block in enumerate(pages, 1):
        if probe and probe in _norm(block):
            printed = PRINTED_PAGE.search(block)
            return f"PDF p. {index}" + (f", printed p. {printed.group(1)}" if printed else "")
    return None


def validate(reqs: List[Dict[str, Any]], indicator_ids: set, domains: set, codes: set, sources_dir: Path) -> List[str]:
    """Return a list of validation errors."""
    errors: List[str] = []
    ids = [r["id"] for r in reqs]
    errors += [f"duplicate id {i}" for i in {i for i in ids if ids.count(i) > 1}]
    cache: Dict[str, str] = {}
    for r in reqs:
        rid = r["id"]
        path = sources_dir / r["file"]
        if not path.exists():
            errors.append(f"{rid}: source file missing {r['file']}")
            continue
        text = cache.setdefault(r["file"], _norm(path.read_text(encoding="utf-8")))
        errors += [f"{rid}: quote not found verbatim in {r['file']}: {q[:60]!r}" for q in r["quotes"] if _norm(q) not in text]
        errors += [f"{rid}: unknown indicator {i}" for i in r["indicators"] if i not in indicator_ids]
        errors += [f"{rid}: unknown domain {d}" for d in r["domains"] if d not in domains]
        if r["measurability"] not in codes:
            errors.append(f"{rid}: unknown measurability {r['measurability']}")
    return errors


def render(reqs: List[Dict[str, Any]], records: List[Dict[str, Any]], schema_domains: Dict[str, str], sources_dir: Path, meta: Dict[str, Any]) -> str:
    """Render the Assurance Taxonomy and Control Matrix as markdown."""
    nist_text = (sources_dir / "nist_ai_100_1.txt").read_text(encoding="utf-8")
    pccp_text = (sources_dir / "fda_pccp_guidance.txt").read_text(encoding="utf-8")
    lines = ["# Assurance Taxonomy and Control Matrix (Phase I output, partial)", "",
             "Generated by `scripts/validate_requirements.py` from `phase1/requirements.yaml`. Every quote below was "
             "checked as a verbatim substring of the saved source text. Coding of measurability is by a single coder "
             "(the assistant) and has not been independently reviewed.", "",
             "## 1. Requirements and their measurability", "",
             "| ID | Source | Locator | Measurability | Domains | CCA indicators |", "|---|---|---|---|---|---|"]
    for r in reqs:
        locator = r["locator"]
        texts = {"S1": nist_text, "S3": pccp_text}
        if r["source"] in texts and (page := locate_page(texts[r["source"]], r["quotes"][0])):
            locator += f", {page}"
        lines.append(f"| {r['id']} | {r['source']} | {locator} | {r['measurability']} | {', '.join(r['domains']) or '-'} | {', '.join(r['indicators']) or '-'} |")
    lines += ["", "Measurability codes:", ""] + [f"- `{k}`: {v}" for k, v in meta["measurability"].items()]
    lines += ["", "## 2. Quoted text and notes", ""]
    for r in reqs:
        lines += [f"**{r['id']}** ({r['source']}, {r['locator']}). " + " / ".join(f"\"{q}\"" for q in r["quotes"]), f"Note: {r['note']}", ""]
    by_domain: Dict[str, List[str]] = defaultdict(list)
    for r in reqs:
        for d in r["domains"]:
            by_domain[d].append(r["id"])
    lines += ["## 3. Coverage by assurance domain", "", "| Domain | Requirements anchoring it | n |", "|---|---|---|"]
    lines += [f"| {d}: {title} | {', '.join(by_domain[d]) or '-'} | {len(by_domain[d])} |" for d, title in schema_domains.items()]
    anchored = {i for r in reqs for i in r["indicators"]}
    unanchored = [r["id"] for r in records if r["id"] not in anchored]
    lines += ["", "## 4. Indicators with no anchor in the retrieved requirements", "",
              f"{len(unanchored)} of {len(records)} indicators are not mapped from any requirement extracted from the retrieved sources: "
              + ", ".join(unanchored) + ".", "",
              "This does not show that the sources omit them. It shows that the passages extracted here do not name them, "
              "and that the retrieval was partial (see section 5).", "", "## 5. Sources and retrieval status", ""]
    lines += [f"- **{k}**: {v}" for k, v in meta["sources"].items()]
    lines += ["", "Not retrieved in this session:", ""] + [f"- {x}" for x in meta["not_retrieved"]]
    return "\n".join(lines) + "\n"


def main() -> int:
    """Validate and render."""
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    reqs = yaml.safe_load((PHASE1 / "requirements.yaml").read_text(encoding="utf-8"))
    meta = yaml.safe_load((PHASE1 / "requirements_schema.yaml").read_text(encoding="utf-8"))
    schema = load_schema(INDICATOR_DIR / "schema.yaml")
    records = load_records(INDICATOR_DIR)
    errors = validate(reqs, {r["id"] for r in records}, set(schema.domains), set(meta["measurability"]), PHASE1 / "sources")
    for e in errors:
        logger.error(e)
    if errors:
        return 1
    OUTPUT.write_text(render(reqs, records, schema.domains, PHASE1 / "sources", meta), encoding="utf-8")
    logger.info("Validated %d requirements; wrote %s", len(reqs), OUTPUT.name)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
