"""Validate the observables map (milestone M0) and render phase2/Observables-Map.md.

Usage: python scripts/validate_observables.py
Exit status is non-zero when any data element is unmapped or maps to an unknown output.
"""

import logging
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.sim_module.observables import indicator_status, load_indicators, load_observables, validate_observables  # noqa: E402

logger = logging.getLogger(__name__)
OUTPUT = Path(__file__).resolve().parent.parent / "phase2" / "Observables-Map.md"


def main() -> int:
    """Validate and render."""
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    records, obs = load_indicators(), load_observables()
    errors = validate_observables(records, obs)
    for e in errors:
        logger.error(e)
    if errors:
        return 1
    status = indicator_status(records, obs)
    ready = [i for i, s in status.items() if s["testable_now"]]
    by_module = Counter(v["module"] for v in obs["outputs"].values() if v["status"] == "planned")
    needs = Counter(o for s in status.values() for o in s["missing_outputs"])
    lines = ["# Observables map (milestone M0)", "",
             "Generated by `scripts/validate_observables.py` from `phase2/observables.yaml`. Each data element an indicator needs "
             "is mapped to a simulator output. An indicator can be tested only when every output it needs is implemented.", "",
             f"{len(ready)} of {len(status)} predictive-applicable indicators are testable with the current data and model layer: {', '.join(ready)}.", "",
             "## Indicators and what they still need", "", "| Indicator | Testable now | Outputs needed | Missing (planned) |", "|---|---|---|---|"]
    lines += [f"| {i} | {'yes' if s['testable_now'] else 'no'} | {', '.join(s['outputs'])} | {', '.join(s['missing_outputs']) or '-'} |" for i, s in status.items()]
    lines += ["", "## Planned outputs by layer", "", "| Layer | Planned outputs |", "|---|---|"]
    lines += [f"| {m} | {n} |" for m, n in sorted(by_module.items())]
    lines += ["", "## Planned outputs ranked by number of indicators blocked", "", "| Output | Indicators blocked |", "|---|---|"]
    lines += [f"| {o} | {n} |" for o, n in needs.most_common()]
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    logger.info("%d of %d indicators testable now; wrote %s", len(ready), len(status), OUTPUT.name)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
